### create list
POST http://localhost:8000/lists
Content-Type: application/json

{
  "name": "lista dois!!"
}

### get lits
GET http://localhost:8000/lists

### get lits
GET http://localhost:8000/lists/1

### update list
PATCH  http://localhost:8000/lists/1
Content-Type: application/json

{
  "name": "lista um!!"
}

### list lits
DELETE  http://localhost:8000/lists/10




### get tasks
GET http://localhost:8000/tasks

### 
POST http://localhost:8000/tasks
Content-Type: application/json

{
  "title": "titulo teste 4",
  "description": "descicao teste 4",
  "priority": "VERY_HIGH",
  "listId": 3
}

###
DELETE http://localhost:8000/tasks/11



###

PATCH http://localhost:8000/tasks/3
Content-Type: application/json

{
  "title": "title updated"
}